// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEYCuMks8hg9G0wDTEqX8g2QXOv3oPyGY',
    appId: '1:49061877090:web:85018927b340b74a94c83b',
    messagingSenderId: '49061877090',
    projectId: 'e-shop-40405',
    authDomain: 'e-shop-40405.firebaseapp.com',
    storageBucket: 'e-shop-40405.firebasestorage.app',
    measurementId: 'G-7CBEEVGKQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWuHQy4DsrR1S7xDSEgHawVudIIsrYzn0',
    appId: '1:49061877090:android:104c6e5ceb44bf9394c83b',
    messagingSenderId: '49061877090',
    projectId: 'e-shop-40405',
    storageBucket: 'e-shop-40405.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBaVvcRh6HryUHTpGcA8fUHKT40EkG-I0',
    appId: '1:49061877090:ios:f6818a7a5af0883d94c83b',
    messagingSenderId: '49061877090',
    projectId: 'e-shop-40405',
    storageBucket: 'e-shop-40405.firebasestorage.app',
    iosBundleId: 'com.chhairinsarorn.eShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBaVvcRh6HryUHTpGcA8fUHKT40EkG-I0',
    appId: '1:49061877090:ios:524a2d6e233d4e0a94c83b',
    messagingSenderId: '49061877090',
    projectId: 'e-shop-40405',
    storageBucket: 'e-shop-40405.firebasestorage.app',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEYCuMks8hg9G0wDTEqX8g2QXOv3oPyGY',
    appId: '1:49061877090:web:faeb8f2d987e1c6e94c83b',
    messagingSenderId: '49061877090',
    projectId: 'e-shop-40405',
    authDomain: 'e-shop-40405.firebaseapp.com',
    storageBucket: 'e-shop-40405.firebasestorage.app',
    measurementId: 'G-M9N1MEH55N',
  );
}
