# Podfile for e_shop
# កំណត់ Version iOS ទាបបំផុតដែល Google Maps support (ផ្ដល់អនុសាសន៍ ១៤.០)
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  # បន្ថែម :linkage => :static ដើម្បីឱ្យ Google Maps ដំណើរការបានស្រួលជាមួយ Swift
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
#     target.build_configurations.each do |config|
#       # ដោះស្រាយបញ្ហា No such module 'GoogleMaps' ដោយកំណត់ Deployment Target ឱ្យដូចគ្នាទាំងអស់
#       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
#
#       # សម្រាប់អ្នកប្រើ Mac M1/M2/M3 ដើម្បីឱ្យ Run លើ Simulator បាន
#       config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
#       config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
#     end
  end
end