name: Build Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Create .env
        shell: pwsh
        run: |
          @"
          APP_NAME=My E Shop
          APP_ENV=production
          API_BASE_URL=https://e-shop-1-m034.onrender.com/api/v1
          TIMEOUT=30
          MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}
          "@ | Out-File -FilePath .env -Encoding utf8

      - name: Build Windows
        run: flutter build windows --release

      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive `
            -Path build/windows/x64/runner/Release/* `
            -DestinationPath E-Shop-v1.0.0-Windows.zip

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: E-Shop-Windows
          path: E-Shop-v1.0.0-Windows.zip